knp_paginator:
    page_range: 5                       # nombre de liens montrer dans la menu de pagination (par exemple: si il y a 10 pages, un page_range de 3, sur la 5Ã¨me page on pourra voir les liens des pages 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: ~              # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template